### ISSUE TITLE
Iterative strategy

### ISSUE THREAD

**Issue by L-Fatia** [wyy-code/PiPEA#1]
Thank you for your interesting work. It seems that the iterative strategy mentioned in the experimental section is not implemented in the provided code. Could you please upload the implementation of this strategy? Thank you!

**Comment by wyy-code** [comment]
Thank you for your attention to PipEA~ We have updated the PipEA.py to include the iterative strategy. Please note that PipEA.py encompasses the entire process, including training the encoders, performing potential isomorphism propagation, and adopting iterative training. If you wish to test other models, such as Dual-AMN, more quickly, you can train the encoders first and then directly feed the entity embedding into test.py.

Best wishes.

**Comment by JUN000317** [comment]
Hello, after using your iterative strategy, the performance of my model has decreased, and I am unable to achieve the results mentioned in the paper. Could you please help me identify where the issue might be? I would greatly appreciate your assistance. Wishing you good health and success in your work.
